# Generated by Django 5.2.10 on 2026-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0002_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
