# Generated by Django 5.2.10 on 2026-01-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
